const books = [
  {
    "id": 1,
    "title": "1984",
    "author": "George Orwell",
    "year": 1949,
    "genre": "Dystopian Fiction",
    "pages": 328,
    "irating": 4.5,
    "imageUrl":'https://th.bing.com/th/id/OIP.8weipgxeZASSI2nt9APKNAAAAA?w=184&h=281&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'Set in the fictional Oceanian colony of Airstrip One (formally Britain), the narrative charts the fall of rebellious propagandist Winston Smith. Written as he lay dying of tuberculosis, the novel illustrates Orwell’s fears for the future in the aftermath of World War II.'
  },
  {
    "id": 2,
    "title": "Brave New World",
    "author": "Aldous Huxley",
    "year": 1932,
    "genre": "Science Fiction",
    "pages": 311,
    "irating": 4.3,
    "imageUrl":'https://th.bing.com/th/id/OIP.1RBVmaZim9kwmq-ygghdzwHaJl?w=184&h=239&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'Brave New World is a dystopian novel written by the English author Aldous Huxley in 1931 and published in 1932. It imagines a futuristic World State where people are genetically engineered, socially conditioned, and divided into castes.'
  },
  {
    "id": 3,
    "title": "To Kill a Mockingbird",
    "author": "Harper Lee",
    "year": 1960,
    "genre": "Classic",
    "pages": 281,
    "irating": 4.8,
    "imageUrl":'https://th.bing.com/th/id/OIP.WcFQE6IDtrVRU17IMTnFWQHaLH?w=184&h=276&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'It tells the story of Scout Finch, a young girl in the racially charged American South of the 1930s, and her father, Atticus Finch, who is a lawyer defending a black man falsely accused. The novel explores themes of racial injustice, moral growth, and the innocence of childhood.'
  },
  {
    "id": 4,
    "title": "The Great Gatsby",
    "author": "F. Scott Fitzgerald",
    "year": 1925,
    "genre": "Classic",
    "pages": 180,
    "irating": 4.4,
    "imageUrl":'https://th.bing.com/th/id/OIP.jDIJ9apUZ-DWPYSmYCtgBgHaLH?w=184&h=276&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'In " The Great Gatsby," Nick Carraway narrates the rise and fall of Jay Gatsby, a wealthy man trying to win back his former love, Daisy Buchanan.'
  },
  {
    "id": 5,
    "title": "Moby Dick",
    "author": "Herman Melville",
    "year": 1851,
    "genre": "Adventure",
    "pages": 635,
    "irating": 3.9,
    "imageUrl":'https://th.bing.com/th/id/OIP.CuwsZnyJ6b2xaBZdKzDhdQHaLx?w=184&h=293&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'Mocha Dick, a real-life male sperm whale that lived in the Pacific Ocean waters near Mocha Island during the 1800s.'
  },
  {
    "id": 6,
    "title": "War and Peace",
    "author": "Leo Tolstoy",
    "year": 1869,
    "genre": "Historical Fiction",
    "pages": 1225,
    "irating": 4.2,
    "imageUrl":'https://th.bing.com/th/id/OIP.KCHV-zzLV3Umy_QoyIJyLgHaLZ?w=184&h=284&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'Set during the Napoleonic Wars, exploring themes of history, society, and human experience through the lives of several Russian aristocratic families.'
  },
  {
    "id": 7,
    "title": "Pride and Prejudice",
    "author": "Jane Austen",
    "year": 1813,
    "genre": "Romance",
    "pages": 279,
    "irating": 4.7,
    "imageUrl":'https://th.bing.com/th/id/OIP.wcZjPkH4FZD5QYi_2kfxxAHaLS?w=184&h=281&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'Set in 19th-century rural England, the novel deals with the issues of manners, upbringing, morality, education, and marriage in the society of the landed gentry.'
  },
  {
    "id": 8,
    "title": "The Catcher in the Rye",
    "author": "J.D. Salinger",
    "year": 1951,
    "genre": "Coming-of-Age",
    "pages": 277,
    "irating": 4.1,
    "imageUrl":'https://th.bing.com/th/id/OIP.S_x2cmbtyYMi8jk6uJjt6QHaJV?w=184&h=232&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'The novel details two days in the life of 16-year-old Holden Caulfield after he has been expelled from prep school. Confused and disillusioned, Holden searches for truth and rails against the “phoniness” of the adult world.'
  },
  {
    "id": 9,
    "title": "The Hobbit",
    "author": "J.R.R. Tolkien",
    "year": 1937,
    "genre": "Fantasy",
    "pages": 310,
    "irating": 4.6,
    "imageUrl":'https://th.bing.com/th/id/OIP.7H4xRRIZLyY8WCXQEfTQ7wHaKe?w=184&h=260&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'"The Hobbit" follows Bilbo Baggins, a hobbit who embarks on an unexpected adventure with a group of dwarves to reclaim their treasure from the dragon Smaug.'
  },
  {
    "id": 10,
    "title": "Fahrenheit 451",
    "author": "Ray Bradbury",
    "year": 1953,
    "genre": "Science Fiction",
    "pages": 249,
    "irating": 4.4,
    "imageUrl":'https://th.bing.com/th/id/OIP.bbHa01bP9EvGaSHY8vNWnwHaLP?w=184&h=281&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'Fahrenheit 451 is a 1953 dystopian novel by American writer Ray Bradbury. It presents a future American society that explores the dangers of censorship and the suppression of individual thought in a future society where books are banned and "firemen" burn any that are found.'
  },
  {
    "id": 11,
    "title": "The Lord of the Rings",
    "author": "J.R.R. Tolkien",
    "year": 1954,
    "genre": "Fantasy",
    "pages": 1178,
    "irating": 4.9,
    "imageUrl":'https://th.bing.com/th/id/OIP.7BdS1txSlzfvUxzC4rOgpgHaLp?w=184&h=289&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'Set in the fictional land of Middle-earth, "The Lord of the Rings" follows the perilous quest of a diverse group of characters to destroy the One Ring and defeat the dark lord Sauron. The story begins in the Shire, a peaceful and idyllic land inhabited by the hobbits, a small and unassuming race.'
  },
  {
    "id": 12,
    "title": "Harry Potter and the Sorcerer's Stone",
    "author": "J.K. Rowling",
    "year": 1997,
    "genre": "Fantasy",
    "pages": 309,
    "irating": 4.7,
    "imageUrl":'https://th.bing.com/th/id/OIP.QBwDcEXXCGPUIu-sL4UQjgHaMi?w=184&h=311&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'The main plot follows Harry Potter, a young boy who discovers he is a wizard on his 11th birthday and attends Hogwarts School of Witchcraft and Wizardry, where he learns about his magical heritage and faces the dark wizard Voldemort.'
  },
  {
    "id": 13,
    "title": "The Hitchhiker's Guide to the Galaxy",
    "author": "Douglas Adams",
    "year": 1979,
    "genre": "Science Fiction",
    "pages": 193,
    "irating": 4.6,
    "imageUrl":'https://th.bing.com/th/id/OIP.x9iZuOIeOxRKkB8V4ayzQQHaKw?w=182&h=265&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'The Hitchhiker’s Guide to the Galaxy is a comedic science fiction novel by British author Douglas Adams, first published in 1979. The novel follows the misadventures of the hapless human Arthur Dent after he is saved from Earth’s destruction by Ford Prefect, a friend who turns out to be an alien.'
  },
  {
    "id": 14,
    "title": "Dune",
    "author": "Frank Herbert",
    "year": 1965,
    "genre": "Science Fiction",
    "pages": 412,
    "irating": 4.6,
    "imageUrl":'https://th.bing.com/th/id/OIP.GhuATIepkEQb5LdxgUq0YwHaKN?w=184&h=254&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'Dune is the story of an "offworld" noble Family. Their world is violently shattered, but their young scion adapts to the ways of his new planet, assumes religious and military leadership, optimizes his powers of prescience to see the plot against him, and utterly defeats his foes.'
  },
  {
    "id": 15,
    "title": "The Chronicles of Narnia",
    "author": "C.S. Lewis",
    "year": 1950,
    "genre": "Fantasy",
    "pages": 767,
    "irating": 4.5,
    "imageUrl":'https://th.bing.com/th/id/OIP.HQUHQDwEdebKHFoxdZlxpwHaLB?w=184&h=274&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'The Chronicles of Narnia is a series of fantasy novels that follow the adventures of a group of children who stumble upon a magical world called Narnia. They encounter talking animals, mythical creatures, and embark on quests to save the land from evil forces.'
  },
  {
    "id": 16,
    "title": "Don Quixote",
    "author": "Miguel de Cervantes",
    "year": 1605,
    "genre": "Classic",
    "pages": 863,
    "irating": 4.1,
    "imageUrl":'https://th.bing.com/th/id/OIP.O81ZQuETMhqKoyAlV-3FRAHaJ_?w=184&h=248&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'Don Quixote is a middle-aged gentleman from the region of La Mancha in central Spain. Obsessed with the chivalrous ideals touted in books he has read, he decides to take up his lance and sword to defend the helpless and destroy the wicked.'
  },
  {
    "id": 17,
    "title": "The Odyssey",
    "author": "Homer",
    "year": -800,
    "genre": "Epic Poetry",
    "pages": 448,
    "irating": 4.3,
    "imageUrl":'https://th.bing.com/th/id/OIP.1WxbIygs1IVKVOuQJFDVxgHaLc?w=184&h=284&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'"The Odyssey" by Homer, translated by George Herbert Palmer, is an epic poem that follows the hero Odysseus on his journey home after the Trojan War, facing various obstacles and adventures while striving to reunite with his family.'
  },
  {
    "id": 18,
    "title": "Crime and Punishment",
    "author": "Fyodor Dostoevsky",
    "year": 1866,
    "genre": "Psychological Fiction",
    "pages": 671,
    "irating": 4.6,
    "imageUrl":'https://th.bing.com/th/id/OIP.B4i5nOQbmkv3IYOviTpXGAHaLH?w=184&h=276&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'Crime and Punishment was first published in 1866 by Russian novelist Fyodor Dostoevsky. The plot follows the alienation of a student named Raskolnikov, who decides to commit the perfect crime in order to prove his philosophical superiority over others.'
  },
  {
    "id": 19,
    "title": "The Picture of Dorian Gray",
    "author": "Oscar Wilde",
    "year": 1890,
    "genre": "Gothic Fiction",
    "pages": 254,
    "irating": 4.2,
    "imageUrl":'https://th.bing.com/th/id/OIP.f87kvy7StzeacxY7DidHsgAAAA?w=184&h=276&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'Lord Henry gives Dorian a book that describes the wicked exploits of a nineteenth-century Frenchman; it becomes Dorian’s bible as he sinks ever deeper into a life of sin and corruption.'
  },
  {
    "id": 20,
    "title": "One Hundred Years of Solitude",
    "author": "Gabriel García Márquez",
    "year": 1967,
    "genre": "Magical Realism",
    "pages": 417,
    "irating": 4.6,
    "imageUrl":'https://th.bing.com/th/id/OIP.m4tD0LAsRTqAVkfJdbazpQHaLH?w=184&h=276&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'This novel is a multi-generational saga that focuses on the Buendía family, who founded the fictional town of Macondo. It explores themes of love, loss, family, and the cyclical nature of history.'
  },
  {
    "id": 21,
    "title": "Frankenstein",
    "author": "Mary Shelley",
    "year": 1818,
    "genre": "Gothic Fiction",
    "pages": 280,
    "irating": 4.1,
    "imageUrl":'https://th.bing.com/th/id/OIP.VG1OspQyMiLkz9rpH4IoGAHaL1?w=184&h=295&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'"Frankenstein" by Mary Shelley tells the story of Victor Frankenstein, a scientist who creates a living being from dead body parts, only to be horrified by his creation and face tragic consequences.'
  },
  {
    "id": 22,
    "title": "The Alchemist",
    "author": "Paulo Coelho",
    "year": 1988,
    "genre": "Adventure",
    "pages": 163,
    "irating": 4.5,
    "imageUrl":'https://th.bing.com/th/id/OIP.arKz82CzkTMoiWmHRt6fdAAAAA?w=184&h=277&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'The Alchemist, first published in 1988, is a novel by Brazilian writer Paulo Coelho and translated by Alan R. Clarke. It tells the story of Santiago, a shepherd from Andalusia who dreams of a treasure buried beside the pyramids in Egypt.'
  },
  {
    "id": 23,
    "title": "The Grapes of Wrath",
    "author": "John Steinbeck",
    "year": 1939,
    "genre": "Social Realism",
    "pages": 464,
    "irating": 4.3,
    "imageUrl":'https://th.bing.com/th/id/OIP.AX5EzBikU7hPxz6vJaST2wHaKI?w=184&h=252&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":`"The Grapes of Wrath" by John Steinbeck follows the Joad family's harrowing journey from Oklahoma to California during the Great Depression, highlighting themes of poverty, social injustice, and resilience.`
  },
  {
    "id": 24,
    "title": "Jane Eyre",
    "author": "Charlotte Brontë",
    "year": 1847,
    "genre": "Gothic Fiction",
    "pages": 532,
    "irating": 4.4,
    "imageUrl":'https://th.bing.com/th/id/OIP.S6RKGdL1CMPMdj0exmv2agHaL0?w=184&h=294&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'"Jane Eyre" follows the life of an orphaned girl, Jane, who faces adversity and abuse but ultimately finds love and independence through her journey.'
  },
  {
    "id": 25,
    "title": "The Old Man and the Sea",
    "author": "Ernest Hemingway",
    "year": 1952,
    "genre": "Literary Fiction",
    "pages": 127,
    "irating": 4.1,
    "imageUrl":'https://th.bing.com/th/id/OIP.6rq2dUWqexb-Iklqk8TdogHaKe?w=184&h=260&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'"The Old Man and the Sea" is a poignant novella by Ernest Hemingway that tells the story of Santiago, an aging Cuban fisherman, who struggles against a giant marlin in a battle of endurance and resilience.'
  },
  {
    "id": 26,
    "title": "The Road",
    "author": "Cormac McCarthy",
    "year": 2006,
    "genre": "Post-apocalyptic",
    "pages": 241,
    "irating": 4.4,
    "imageUrl":'https://th.bing.com/th/id/OIP.HP0sxZg4iW7BwBLtWoE6dwHaKk?w=184&h=262&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'The Road is post-apocalyptic novel which details the grueling journey of a father and his young son over several months across a landscape blasted by an unspecified cataclysm that has destroyed industrial civilization and nearly all life. '
  },
  {
    "id": 27,
    "title": "The Shining",
    "author": "Stephen King",
    "year": 1977,
    "genre": "Horror",
    "pages": 447,
    "irating": 4.6,
    "imageUrl":'https://th.bing.com/th/id/OIP.kPE_GACF2Z99y8AcTPQDhgAAAA?w=184&h=284&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'The Shining is a 1977 horror novel which tells the story of Jack, Wendy, and Danny Torrance during an isolated winter in which Jack becomes the caretaker of Colorado’s Overlook Hotel. It deals with themes of parenthood, isolation, addiction, and the bonds of family.'
  },
  {
    "id": 28,
    "title": "Dracula",
    "author": "Bram Stoker",
    "year": 1897,
    "genre": "Gothic Horror",
    "pages": 418,
    "irating": 4.2,
    "imageUrl":'https://th.bing.com/th/id/OIP.zLsdxLcYKjumkkcZc0h32AHaL6?w=184&h=295&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":`"Dracula" by Bram Stoker follows the harrowing journey of Jonathan Harker as he encounters the sinister Count Dracula, leading to a battle against the vampire's dark influence in England.`
  },
  {
    "id": 29,
    "title": "The Martian",
    "author": "Andy Weir",
    "year": 2011,
    "genre": "Science Fiction",
    "pages": 387,
    "irating": 4.7,
    "imageUrl":'https://th.bing.com/th/id/OIP.AEyz_yWxvQgxqOMKQTdtGQHaMW?w=184&h=307&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'"The Martian" by Andy Weir is a novel about Mark Watney, an astronaut who is accidentally left behind on Mars after a dust storm forces his crew to evacuate, presuming him dead. The story follows his struggle for survival on the barren planet.'
  },
  {
    "id": 30,
    "title": "The Hunger Games",
    "author": "Suzanne Collins",
    "year": 2008,
    "genre": "Young Adult",
    "pages": 374,
    "irating": 4.5,
    "imageUrl":'https://th.bing.com/th/id/OIP.lErxPNRuZBqoYcvKcnI3EQHaLb?w=184&h=284&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":`"The Hunger Games" by Suzanne Collins follows Katniss Everdeen, a 16-year-old girl who volunteers to take her sister's place in a deadly competition known as the Hunger Games, set in a dystopian future called Panem.`
  },
  {
    "id": 31,
    "title": "The Da Vinci Code",
    "author": "Dan Brown",
    "year": 2003,
    "genre": "Thriller",
    "pages": 454,
    "irating": 3.8,
    "imageUrl":'https://th.bing.com/th/id/OIP.-ZNE9JeDO1eYEvTgLRviVwAAAA?w=184&h=301&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":`"The Da Vinci Code" follows symbologist Robert Langdon and cryptologist Sophie Neveu as they unravel a murder mystery in the Louvre, leading them to secrets about the Holy Grail and a hidden bloodline of Jesus Christ.`
  },
  {
    "id": 32,
    "title": "Gone Girl",
    "author": "Gillian Flynn",
    "year": 2012,
    "genre": "Thriller",
    "pages": 415,
    "irating": 4.2,
    "imageUrl":'https://th.bing.com/th/id/OIP.JEiAC9E-2lDZZFjZVnX9vAHaLU?w=184&h=281&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":`"Gone Girl" by Gillian Flynn is a psychological thriller that explores the complexities of marriage and the dark side of human nature through the disappearance of Amy Dunne on her fifth wedding anniversary.`
  },
  {
    "id": 33,
    "title": "The Girl with the Dragon Tattoo",
    "author": "Stieg Larsson",
    "year": 2005,
    "genre": "Mystery",
    "pages": 464,
    "irating": 4.1,
    "imageUrl":'https://th.bing.com/th/id/OIP.ubEVEsnTOqCnHwsbfsiOxAHaJ4?w=184&h=245&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":`This gripping novel follows journalist Mikael Blomkvist and hacker Lisbeth Salander as they investigate the disappearance of Harriet Vanger, who vanished over forty years ago. Their journey into dark secrets reveals corruption and violence hidden within a wealthy family.`
  },
  {
    "id": 34,
    "title": "The Shadow of the Wind",
    "author": "Carlos Ruiz Zafón",
    "year": 2001,
    "genre": "Gothic",
    "pages": 487,
    "irating": 4.4,
    "imageUrl":'https://th.bing.com/th/id/OIP.JLX1Mofsn9eKXG7Xdeu9KQAAAA?w=184&h=284&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":`"The Shadow of the Wind" by Carlos Ruiz Zafón is a captivating tale set in post-Civil War Barcelona, where a young boy named Daniel Sempere discovers a mysterious book that leads him on a quest to uncover its enigmatic author, Julián Carax, and the dark secrets surrounding his life.`
  },
  {
    "id": 35,
    "title": "Outlander",
    "author": "Diana Gabaldon",
    "year": 1991,
    "genre": "Historical Fiction",
    "pages": 850,
    "irating": 4.5,
    "imageUrl":'https://th.bing.com/th/id/OIP.lNGE8b3lvfBbEuBCOFSGywHaLp?w=184&h=289&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'This book tells the story of Claire Randall, a combat nurse who time-travels from 1945 to 1743 Scotland. During her adventure, she encounters clan battles, political intrigue, and deep love.'
  },
  {
    "id": 36,
    "title": "Ready Player One",
    "author": "Ernest Cline",
    "year": 2011,
    "genre": "Science Fiction",
    "pages": 374,
    "irating": 4.3,
    "imageUrl":'https://th.bing.com/th/id/OIP.XPl5ZMsB3mmqvhJpEjfJSwHaLW?w=184&h=283&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'The protagonist, a teenager living in the stacks, who is determined to find the Easter egg in the OASIS. A skilled and resourceful female gunter (Easter egg hunter) who competes with Wade in the hunt for the Easter egg.'
  },
  {
    "id": 37,
    "title": "The Name of the Wind",
    "author": "Patrick Rothfuss",
    "year": 2007,
    "genre": "Fantasy",
    "pages": 662,
    "irating": 4.6,
    "imageUrl":'https://th.bing.com/th/id/OIP.Zcj7ak_heLLzcsa1syUGqAHaLY?w=130&h=200&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'This book tells the story of Kvothe, a once legendary figure now living as an innkeeper. He shares the authentic events of his extraordinary life filled with magic, music, and mischief. '
  },
  {
    "id": 38,
    "title": "The Stand",
    "author": "Stephen King",
    "year": 1978,
    "genre": "Horror",
    "pages": 1152,
    "irating": 4.4,
    "imageUrl":'https://th.bing.com/th/id/OIP.zIFbtiS5PJu1fgMIdRKNnAHaLX?w=184&h=283&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'This book depicts a world ravaged by a deadly plague. The survivors are caught between good and evil, represented by the saintly Mother Abigail and the sinister Randall Flagg. As society crumbles, they must navigate their new reality filled with dark dreams and moral dilemmas.'
  },
  {
    "id": 39,
    "title": "The Secret History",
    "author": "Donna Tartt",
    "year": 1992,
    "genre": "Mystery",
    "pages": 559,
    "irating": 4.2,
    "imageUrl":'https://th.bing.com/th/id/OIP.lnAZK_Z6T0lseBhYWsubwAHaLV?w=184&h=281&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":"In 'The Secret History' by Donna Tartt, a group of elite college students become enmeshed in a world of intellectual pursuit and moral ambiguity. Drawn together by their profound appreciation for classical literature, their camaraderie soon spirals into obsession."
  },
  {
    "id": 40,
    "title": "The Handmaid's Tale",
    "author": "Margaret Atwood",
    "year": 1985,
    "genre": "Dystopian Fiction",
    "pages": 311,
    "irating": 4.2,
    "imageUrl":'https://th.bing.com/th/id/OIP.OlRKeyIkyC1TFHotAmpo9QHaKv?w=184&h=268&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":`"The Handmaid's Tale" by Margaret Atwood is set in a dystopian future where a totalitarian regime called Gilead has replaced the United States, enforcing strict societal roles and subjugating women.`
  },
  {
    "id": 41,
    "title": "A Game of Thrones",
    "author": "George R.R. Martin",
    "year": 1996,
    "genre": "Fantasy",
    "pages": 694,
    "irating": 4.4,
    "imageUrl":'https://th.bing.com/th/id/OIP.rAsglktcnlfnU0ITivkqOAHaLc?w=184&h=284&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":`"A Game of Thrones" is the first book in George R.R. Martin's epic fantasy series "A Song of Ice and Fire," set in the fictional continents of Westeros and Essos, where noble families vie for power and control of the Iron Throne.`
  },
  {
    "id": 42,
    "title": "The Count of Monte Cristo",
    "author": "Alexandre Dumas",
    "year": 1844,
    "genre": "Adventure",
    "pages": 1276,
    "irating": 4.7,
    "imageUrl":'https://th.bing.com/th/id/OIP.QbQFZ7cJLClWW522zeNuDgHaL0?w=184&h=294&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'"The Count of Monte Cristo" is a tale of betrayal, revenge, and redemption, following Edmond Dantès, who is wrongfully imprisoned and seeks vengeance against those who conspired against him.'
  },
  {
    "id": 43,
    "title": "Les Misérables",
    "author": "Victor Hugo",
    "year": 1862,
    "genre": "Historical Fiction",
    "pages": 1463,
    "irating": 4.5,
    "imageUrl":'https://th.bing.com/th/id/OIP.gW2W9ogFiLUzAS7T6nnq2QHaMk?w=184&h=313&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'Examining the nature of law and grace, the novel elaborates upon the history of France, the architecture and urban design of Paris, politics, moral philosophy, antimonarchism, justice, religion, and the types and nature of romantic and familial love.'
  },
  {
    "id": 44,
    "title": "The Hitchhiker's Guide to the Galaxy",
    "author": "Douglas Adams",
    "year": 1979,
    "genre": "Science Fiction",
    "pages": 193,
    "irating": 4.6,
    "imageUrl":'https://th.bing.com/th/id/OIP.lfmKZN9uxIvpOZ775GwnewHaLG?w=131&h=197&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":`"The Hitchhiker's Guide to the Galaxy" is a comedic science fiction novel by Douglas Adams that follows the misadventures of Arthur Dent, the last surviving human, as he navigates the absurdities of the universe after Earth is destroyed.`
  },
  {
    "id": 45,
    "title": "The Name of the Rose",
    "author": "Umberto Eco",
    "year": 1980,
    "genre": "Historical Mystery",
    "pages": 502,
    "irating": 4.1,
    "imageUrl":'https://th.bing.com/th/id/OIP.fu_WI3j8s2qOoh7JbkCccAAAAA?w=127&h=191&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'"The Name of the Rose" is a historical murder mystery set in a 14th-century Italian monastery, where a Franciscan friar investigates a series of mysterious deaths while exploring themes of knowledge, power, and belief.'
  },
  {
    "id": 46,
    "title": "Do Androids Dream of Electric Sheep?",
    "author": "Philip K. Dick",
    "year": 1968,
    "genre": "Science Fiction",
    "pages": 210,
    "irating": 4.2,
    "imageUrl":'https://th.bing.com/th/id/OIP.n6NgG0iHhtiNqveX34zW1QAAAA?w=184&h=286&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'"Do Androids Dream of Electric Sheep?" is a dystopian novel by Philip K. Dick that explores themes of humanity, empathy, and the nature of reality in a post-apocalyptic world.'
  },
  {
    "id": 47,
    "title": "A Clockwork Orange",
    "author": "Anthony Burgess",
    "year": 1962,
    "genre": "Dystopian Fiction",
    "pages": 213,
    "irating": 4.0,
    "imageUrl":'https://th.bing.com/th/id/OIP.hJc0PnIUCrJhG7ZQ2eRqAgHaLW?w=184&h=283&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'A Clockwork Orange takes place in a futuristic city governed by a repressive, totalitarian super-State. In this society, ordinary citizens have fallen into a passive stupor of complacency, blind to the insidious growth of a rampant, violent youth culture.'
  },
  {
    "id": 48,
    "title": "The Outsiders",
    "author": "S.E. Hinton",
    "year": 1967,
    "genre": "Young Adult",
    "pages": 192,
    "irating": 4.6,
    "imageUrl":'https://th.bing.com/th/id/OIP.bVOXPeQ99lX6ULjF7bV0GgHaLy?w=184&h=293&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'"The Outsiders" by S.E. Hinton is a classic coming-of-age novel that explores the lives of two rival teenage groups, the Greasers and the Socs, in 1960s Oklahoma. The novel addresses themes of social class, identity, and the struggles of adolescence.'
  },
  {
    "id": 49,
    "title": "The Sun Also Rises",
    "author": "Ernest Hemingway",
    "year": 1926,
    "genre": "Literary Fiction",
    "pages": 251,
    "irating": 4.0,
    "imageUrl":'https://th.bing.com/th/id/OIP.kUDxnSKtWE9Jbnnq2-DGswHaK9?w=184&h=273&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'The novel follows a group of expatriates living in Paris and traveling to Pamplona, Spain, for the annual bullfighting festival. Through the characters’ interactions and experiences, Hemingway explores themes of disillusionment, lost generation, and the search for meaning in a post-World War I world.'
  },
  {
    "id": 50,
    "title": "Slaughterhouse-Five",
    "author": "Kurt Vonnegut",
    "year": 1969,
    "genre": "Science Fiction",
    "pages": 275,
    "irating": 4.3,
    "imageUrl":'https://th.bing.com/th/id/OIP.T2BIxMHvX6I6SIdlXPa61QHaLZ?w=184&h=284&c=7&r=0&o=7&pid=1.7&rm=3',
    "description":'"Slaughterhouse-Five" by Kurt Vonnegut is a non-linear narrative that follows Billy Pilgrim, an American soldier who becomes "unstuck in time," experiencing moments from his life, including his time as a POW during the firebombing of Dresden.'
  }
];


export default books;